const lastkb= document.getElementById("lastkb");
const trainbtn= document.getElementById("trainbtn");
const generationsinput= document.getElementById("generations");
const starttrainingbtn= document.getElementById("trainbtn");
const populationsizeinput= document.getElementById("populationsize");
const trainingdata= document.getElementById("trainingdata");
const effspan= document.getElementById("eff");
const statusspan= document.getElementById("status");
const qwertyspan= document.getElementById("qwerty");
trainingdata.value=`YouTube is an American social media and online video sharing platform owned by Google. YouTube was founded on February 14, 2005, by Chad Hurley, Jawed Karim, and Steve Chen, who were former employees of PayPal.[7] Headquartered in San Bruno, California, it is the second-most-visited website in the world, after Google. In January 2024, YouTube had more than 2.7 billion monthly active users, who collectively watched more than one billion hours of videos every day.[8] As of May 2019, videos were being uploaded to the platform at a rate of more than 500 hours of content per minute,[9][10] and as of mid-2024, there were approximately 14.8 billion videos in total.[11]

On November 13, 2006, YouTube was purchased by Google for US$1.65 billion (equivalent to $2.39 billion in 2024).[12] Google expanded YouTube's business model from generating revenue through advertisements alone to offering paid content such as movies and exclusive content explicitly produced for YouTube. It also offers YouTube Premium, a paid subscription option for watching content without ads. YouTube incorporated the Google AdSense program, generating more revenue for both YouTube and approved content creators. In 2023, YouTube's advertising revenue totaled $31.7 billion, a 2% increase from the $31.1 billion reported in 2022.[13] From Q4 2023 to Q3 2024, YouTube's combined revenue from advertising and subscriptions exceeded $50 billion.[14]

Since its purchase by Google, YouTube has expanded beyond the core website into mobile apps, network television, games, and the ability to link with other platforms. Video categories on YouTube include music videos, video clips, news, short and feature films, songs, documentaries, movie trailers, teasers, TV spots, live streams, vlogs, and more. Most content is generated by individuals, including collaborations between YouTubers and corporate sponsors. Established media, news, and entertainment corporations have also created and expanded their visibility to YouTube channels to reach bigger audiences.

YouTube has had unprecedented social impact, influencing popular culture, internet trends, and creating multimillionaire celebrities. Despite its growth and success, the platform has been criticized for its facilitation of the spread of misinformation and copyrighted content, routinely violating its users' privacy, excessive censorship, endangering the safety of children and their well-being, and for its inconsistent implementation of platform guidelines.

History
Main article: History of YouTube
See also: Timeline of online video
Founding and initial growth (2005–2006)
The founders of YouTube
Chad Hurley
Chad Hurley
Steve Chen
Steve Chen
Jawed Karim
Jawed Karim
YouTube was founded by Chad Hurley, Jawed Karim, and Steve Chen. The three were early employees at PayPal and had become wealthy after eBay's acquisition of the company.[15] Hurley had studied design at the Indiana University of Pennsylvania, and Chen and Karim studied computer science together at the University of Illinois Urbana-Champaign.[16]

According to a story that has often been repeated in the media, Hurley and Chen developed the idea for YouTube during the early months of 2005, after they had experienced difficulty sharing videos that had been shot at a dinner party at Chen's apartment in San Francisco. Karim did not attend the party and denied that it had occurred, but Chen remarked that the idea that YouTube was founded after a dinner party "was probably very strengthened by marketing ideas around creating a story that was very digestible".[17]

Karim said the inspiration for YouTube came from the Super Bowl XXXVIII halftime show controversy when Janet Jackson's breast was briefly exposed by Justin Timberlake during the halftime show. Karim could not easily find video clips of the incident and the 2004 Indian Ocean tsunami online, which led to the idea of a video-sharing site.[18][19] Hurley and Chen said that the original idea for YouTube was a video version of an online dating service and had been influenced by the website Hot or Not.[17][20] They created posts on Craigslist asking attractive women to upload videos of themselves to YouTube in exchange for a $100 reward.[21] Difficulty in finding enough dating videos led to a change of plans, with the site's founders deciding to accept uploads of any video.[22]


The YouTube logo from launch until 2011, featuring its former slogan Broadcast Yourself
YouTube began as a venture capital–funded technology startup. Between November 2005 and April 2006, the company raised money from various investors, with Sequoia Capital and Artis Capital Management being the largest two.[15][23] YouTube's early headquarters were situated above a pizzeria and a Japanese restaurant in San Mateo, California.[24] In February 2005, the company registered www.youtube.com.[25] The first video was uploaded on April 23, 2005. Titled "Me at the zoo", it shows co-founder Jawed Karim at the San Diego Zoo and can still be viewed on the site.[26][27] The same day, the company launched a public beta and by November, a Nike ad featuring Ronaldinho became the first video to reach one million total views.[28][29] The site exited beta in December 2005, by which time the site was receiving 8 million views a day.[30][31] Clips at the time were limited to 100 megabytes, as little as 30 seconds of footage.[32]

YouTube was not the first video-sharing site on the Internet; Vimeo was founded in November 2004, though that site remained a side project of its developers from CollegeHumor.[33] On December 17, 2005—the same week YouTube exited beta—NBCUniversal Saturday Night Live ran a sketch "Lazy Sunday" by The Lonely Island. Besides helping to bolster ratings and long-term viewership for Saturday Night Live, "Lazy Sunday"'s status as an early viral video helped establish YouTube as an important website.[34] Unofficial uploads of the skit to YouTube drew in more than five million collective views by February 2006 before they were removed when NBCUniversal requested it two months later based on copyright concerns.[35] Despite eventually being taken down, these duplicate uploads of the skit helped popularize YouTube's reach and led to the upload of more third-party content.[36][37] The site grew rapidly; in July 2006, the company announced that more than 65,000 new videos were being uploaded every day and that the site was receiving 100 million video views per day.[38]

The choice of the name youtube.com led to problems for a similarly named website, utube.com. That site's owner, Universal Tube & Rollform Equipment (Universal Tube), filed a lawsuit against YouTube in November 2006, after being regularly overloaded by people looking for YouTube. Universal Tube subsequently changed its website to www.utubeonline.com.[39][40][41]

"Broadcast Yourself" era (2006–2013)
On October 9, 2006, Google announced that they had acquired YouTube for $1.65 billion in Google stock.[42][43] The deal was finalized on November 13, 2006.[44][45] Google's acquisition launched newfound interest in video-sharing sites; IAC, which now owned Vimeo, focused on supporting the content creators to distinguish itself from YouTube.[33] It was at this time that YouTube adopted the slogan "Broadcast Yourself". The company experienced rapid growth. The Daily Telegraph wrote that in 2007, YouTube consumed as much bandwidth as the entire Internet in 2000.[46] By 2010, the company had reached a market share of around 43% and more than 14 billion views of videos, according to comScore.[47] That year, the company simplified its interface to increase the time users would spend on the site.[48]

In 2011, more than three billion videos were being watched each day with 48 hours of new videos uploaded every minute.[49][50][51] Most of these views came from a relatively small number of videos; according to a software engineer at that time, 30% of videos accounted for 99% of views on the site.[52] That year, the company again changed its interface and at the same time, introduced a new logo with a darker shade of red.[53][54] A subsequent interface change, designed to unify the experience across desktop, TV, and mobile, was rolled out in 2013.[55] By that point, more than 100 hours were being uploaded every minute, increasing to 300 hours by November 2014.[56][57]


YouTube's headquarters in San Bruno, California, April 2017
During that time, the company also went through some organizational changes. In October 2006, YouTube moved to a new office in San Bruno, California.[58] Hurley announced that he would be stepping down as chief executive officer of YouTube to take an advisory role and that Salar Kamangar would take over as head of the company in October 2010.[59] In April 2009, YouTube partnered with Vevo.[60] In April 2010, Lady Gaga's "Bad Romance" became the most-viewed video, becoming the first video to reach 200 million views on May 9, 2010.[61]

YouTube faced a major lawsuit by Viacom International in 2011 that nearly resulted in the discontinuation of the website. The lawsuit was filed due to alleged copyright infringement of Viacom's material by YouTube. However, the United States Court of Appeals for the Second Circuit ruled that YouTube was not liable, and thus YouTube won the case in 2012.[62]

Susan Wojcicki's leadership (2014–2023)

YouTube logo from 2015 until 2017
Susan Wojcicki was appointed CEO of YouTube in February 2014.[63] In January 2016, YouTube expanded its headquarters in San Bruno by purchasing an office park for $215 million. The complex has 51,468 square metres (554,000 square feet) of space and can house up to 2,800 employees.[64] YouTube officially launched the "polymer" redesign of its user interfaces based on Material Design language as its default, as well as a redesigned logo that is built around the service's play button emblem in August 2017.[65]

Through this period, YouTube tried several new ways to generate revenue beyond advertisements. In 2013, YouTube launched a pilot program for content providers to offer premium, subscription-based channels.[66][67] This effort was discontinued in January 2018 and relaunched in June, with US$4.99 channel subscriptions.[68][69] These channel subscriptions complemented the existing Super Chat ability, launched in 2017, which allows viewers to donate between $1 and $500 to have their comment highlighted.[70] In 2014, YouTube announced a subscription service known as "Music Key", which bundled ad-free streaming of music content on YouTube with the existing Google Play Music service.[71] The service continued to evolve in 2015 when YouTube announced YouTube Red, a new premium service that would offer ad-free access to all content on the platform (succeeding the Music Key service released the previous year), premium original series, and films produced by YouTube personalities, as well as background playback of content on mobile devices. YouTube also released YouTube Music, a third app oriented towards streaming and discovering the music content hosted on the YouTube platform.[72][73][74]

The company also attempted to create products appealing to specific viewers. YouTube released a mobile app known as YouTube Kids in 2015, which was designed to provide an experience optimized for children. It features a simplified user interface, curated selections of channels featuring age-appropriate content, and parental control features.[75] Also in 2015, YouTube launched YouTube Gaming—a video gaming-oriented vertical and app for videos and live streaming, intended to compete with the Amazon.com-owned Twitch.[76] In April 2018, a shooting occurred at YouTube's headquarters in San Bruno, California, which wounded four and resulted in the death of the shooter.[77]

By February 2017, one billion hours of YouTube videos were being watched every day, and 400 hours worth of videos were uploaded every minute.[8][78] Two years later, the uploads had risen to more than 500 hours per minute.[9] During the COVID-19 pandemic, when most of the world was under stay-at-home orders, usage of services like YouTube significantly increased. Forbes estimated that YouTube accounted for 16% of all internet traffic, as of 2024, up from 11% in 2018, before the pandemic.[79][80] In response to EU officials requesting that such services reduce bandwidth to make sure medical entities had sufficient bandwidth to share information, YouTube and Netflix said they would reduce streaming quality for at least thirty days as to cut bandwidth use of their services by 25% to comply with the EU's request.[81] YouTube later announced that they would continue with this move worldwide: "We continue to work closely with governments and network operators around the globe to do our part to minimize stress on the system during this unprecedented situation."[82]

After a 2018 complaint alleging violations of the Children's Online Privacy Protection Act (COPPA),[83] the company was fined $170 million by the FTC for collecting personal information from minors under the age of 13.[84] YouTube was also ordered to create systems to increase children's privacy.[85][86] Following criticisms of its implementation of those systems, YouTube started treating all videos designated as "made for kids" as liable under COPPA on January 6, 2020.[87][88] Joining the YouTube Kids app, the company created a supervised mode, designed more for tweens, in 2021.[89] Additionally, to compete with TikTok and Instagram Reels, YouTube released YouTube Shorts, a short-form video platform.[90] During that period, YouTube entered disputes with other tech companies. For over a year, in 2018–19, no YouTube app was available for Amazon Fire products.[91] In 2020, Roku removed the YouTube TV app from its streaming store after the two companies were unable to reach an agreement.[92]

After testing earlier in 2021, YouTube removed public display of dislike counts on videos in November 2021, claiming the reason for the removal was, based on its internal research, that users often used the dislike feature as a form of cyberbullying and brigading.[93] While some users praised the move as a way to discourage trolls, others felt that hiding dislikes would make it harder for viewers to recognize clickbait or unhelpful videos and that other features already existed for creators to limit bullying. YouTube co-founder Jawed Karim referred to the update as "a stupid idea", and said that the real reason behind the change was "not a good one, and not one that will be publicly disclosed." He felt that users' ability on a social platform to identify harmful content was essential, saying, "The process works, and there's a name for it: the wisdom of the crowds. The process breaks when the platform interferes with it. Then, the platform invariably declines."[94][95][96] Shortly after the announcement, software developer Dmitry Selivanov created Return YouTube Dislike, an open-source, third-party browser extension for Chrome and Firefox that allows users to see a video's number of dislikes.[97] In a letter published on January 25, 2022, by then YouTube CEO Susan Wojcicki, acknowledged that removing public dislike counts was a controversial decision, but reiterated that she stands by this decision, claiming that "it reduced dislike attacks."[98]

In 2022, YouTube launched an experiment where the company would show users who watched longer videos on TVs a long chain of short unskippable adverts, intending to consolidate all ads into the beginning of a video. Following public outrage over the unprecedented amount of unskippable ads, YouTube "ended" the experiment on September 19 of the same year.[99] In October, YouTube announced that they would be rolling out customizable user handles in addition to channel names, which would also become channel URLs.[100]

Neal Mohan leadership (2023–present)

YouTube logo from August 2017 until February 2025
On February 16, 2023, Wojcicki announced that she would step down as CEO, with Neal Mohan named as her successor. Wojcicki took on an advisory role for Google and parent company Alphabet.[101] Wojcicki died a year and a half later from non-small-cell lung cancer, on August 9, 2024.[102] In late October 2023, YouTube began cracking down on the use of ad blockers on the platform. Users of ad blockers may be given a pop-up warning saying "Video player will be blocked after 3 videos". Users of ad blockers are shown a message asking them to allow ads or inviting them to subscribe to the ad-free YouTube Premium subscription plan. YouTube says that the use of ad blockers violates its terms of service.[103][104] In April 2024, YouTube announced it would be "strengthening our enforcement on third-party apps that violate YouTube's Terms of Service, specifically ad-blocking apps".[105] Starting in June 2024, Google Chrome announced that it would be replacing Manifest V2 in favor of Manifest V3, effectively killing support for most ad-blockers.[106] Around the same time, YouTube started using server-side ad injection, which allows the platform to inject the ads directly into the video, instead of having the ad as a separate file which can be blocked.[107]

In September 2023, YouTube announced an in-app gaming platform called Playables. It was made accessible to all users in May 2024, expanding from an initial offering limited to premium subscribers. In December 2024, YouTube began testing a new multiplayer feature for that service, supporting multiplayer functionality across desktop and mobile devices. As of December 2024 the Playables catalog has over 130 games in various genres, including trivia, action and sports.[108][109] In December 2024, YouTube introduced new guidelines prohibiting videos with clickbait titles to enhance content quality and combat misinformation. The platform aims to penalize creators using misleading or sensationalized titles, with potential actions including video removal or channel suspension.[110] According to YouTube, this guideline will gradually roll out in India first, but will expand to more countries in the coming months.[111]

On February 14, 2025, YouTube celebrated 20 years since its founding.[112] On July 30, 2025, amid the implementation of the Online Safety Act 2023 in the United Kingdom, Google announced that it would begin to enforce "age assurance" policies for selected users in the United States as a trial. Machine learning will be used to determine the age of the user (regardless of any account information indicating their age) and restrict access to certain content and features across all Google properties, including YouTube (including, in particular, disabling personalized advertising and enabling certain digital wellbeing limits), if they are assumed to be under 18. On YouTube, this will be based on factors such as searches and video history, and the age of the account. The user must go through age verification via payment, scanned ID, or selfie to access all features if they are detected to be a minor.[113][114] On April 9, 2025, YouTube expressed support for the NO FAKES Act of 2025, introduced by Senator Chris Coons (D-DE) and Senator Marsha Blackburn (R-TN), and announced an expansion of its pilot program that is designed to identify content generated by AI.[115]

On September 23, 2025, YouTube parent company Alphabet announced that it would reinstate creators that were banned for spreading misinformation about COVID-19 and the 2020 U.S. presidential election.[116] Within the context of the suspension of Jimmy Kimmel and debates about free speech in the United States, Vice President JD Vance defended Kimmel's suspension and instead cited a letter sent by Alphabet legal counsel Daniel F. Donovan to U.S. House Judiciary Committee chairman Jim Jordan, claiming the Biden administration pressured YouTube to remove "non-violative user-generated content" containing misinformation about the COVID-19 pandemic and the 2020 election, and announced that it would reinstate content creators previously banned due to the cited content;[117][118] however, such claims have not formally been proven, and the U.S. Supreme Court dismissed in 2024 the First Amendment case Murthy v. Missouri (which claimed the Biden administration had pressured social media companies to censor conservative views, government criticism, and COVID-19 misinformation), ruling 6–3 that neither the attorneys general of Missouri and Louisiana nor other respondents had standing to bring the case. The decision of Alphabet to bring back YouTube creators who engaged in misinformation was criticized for prioritizing "free expression" over "facts".[119]

Senior leadership
YouTube has been led by a CEO since its founding in 2005, beginning with Chad Hurley, who led the company until 2010. After Google's acquisition of YouTube, the CEO role was retained. Salar Kamangar took over Hurley's position and kept the job until 2014. He was replaced by Susan Wojcicki, who later resigned in 2023.[101] On February 16, 2023, Neal Mohan was appointed as the new CEO.[101]

Features
Main article: List of YouTube features
YouTube offers different features based on user verification, such as standard or basic features like uploading videos, creating playlists, and using YouTube Music, with limits based on daily activity (verification via phone number or channel history increases feature availability and daily usage limits); intermediate or additional features like longer videos (over 15 minutes), live streaming, custom thumbnails, and creating podcasts; advanced features like content ID appeals, embedding live streams, applying for monetization, clickable links, adding chapters, and pinning comments on videos or posts.[120]

Videos
Main article: List of YouTube videos
In January 2012, it was estimated that visitors to YouTube spent an average of 15 minutes a day on the site, in contrast to the four or five hours a day spent by a typical US citizen watching television.[121] In 2017, viewers on average watched YouTube on mobile devices for more than an hour every day.[122] In December 2012, two billion views were removed from the view counts of Universal and Sony music videos on YouTube, prompting a claim by The Daily Dot that the views had been deleted due to a violation of the site's terms of service, which ban the use of automated processes to inflate view counts. That was disputed by Billboard, which said that the two billion views had been moved to Vevo, since the videos were no longer active on YouTube.[123][124]

On August 5, 2015, YouTube patched the formerly notorious behavior which caused a video's view count to freeze at "301" (later "301+") until the actual count was verified to prevent view count fraud.[125] YouTube view counts again began updating in real time.[126] Since September 2019, subscriber counts are abbreviated. Only three leading digits of channels' subscriber counts are indicated publicly, compromising the function of third-party real-time indicators such as Social Blade. Exact counts remain available to channel operators inside YouTube Studio.[127]

On November 11, 2021, after testing out this change in March of the same year, YouTube announced it would start hiding dislike counts on videos, making them invisible to viewers. The company stated the decision was in response to experiments which confirmed that smaller YouTube creators were more likely to be targeted in dislike brigading and harassment. Creators will still be able to see the number of likes and dislikes in the YouTube Studio dashboard tool, according to YouTube.[128][129][130] YouTube has an estimated 14.8 billion videos with about 4% of those never having a view.[11] Just over 85% have fewer than 1,000 views.[131]

Copyright issues
Main article: YouTube copyright issues
Further information: § Revenue to copyright holders
YouTube has faced numerous challenges and criticisms in its attempts to deal with copyright, including the site's first viral video, Lazy Sunday, which had to be taken down, due to copyright concerns.[132] At the time of uploading a video, YouTube users are shown a message asking them not to violate copyright laws.[133] Despite this advice, many unauthorized clips of copyrighted material remain on YouTube. YouTube does not view videos before they are posted online, and it is left to copyright holders to issue a DMCA takedown notice pursuant to the terms of the Online Copyright Infringement Liability Limitation Act. Any successful complaint about copyright infringement results in a YouTube copyright strike. Three successful complaints for copyright infringement against a user account will result in the account and all of its uploaded videos being deleted.[134][135] From 2007 to 2009 organizations including Viacom, Mediaset, and the English Premier League have filed lawsuits against YouTube, claiming that it has done too little to prevent the uploading of copyrighted material.[136][137][138]

In August 2008, a US court ruled in Lenz v. Universal Music Corp. that copyright holders cannot order the removal of an online file without first determining whether the posting reflected fair use of the material.[139] YouTube's owner Google announced in November 2015 that they would help cover the legal cost in select cases where they believe fair use defenses apply.[140] In the 2011 case of Smith v. Summit Entertainment LLC, professional singer Matt Smith sued Summit Entertainment for the wrongful use of copyright takedown notices on YouTube.[141] He asserted seven causes of action, and four were ruled in Smith's favor.[142] In April 2012, a court in Hamburg ruled that YouTube could be held responsible for copyrighted material posted by its users.[143] On November 1, 2016, the dispute with GEMA was resolved, with Google content ID being used to allow advertisements to be added to videos with content protected by GEMA.[144]

In April 2013, it was reported that Universal Music Group and YouTube have a contractual agreement that prevents content blocked on YouTube by a request from UMG from being restored, even if the uploader of the video files a DMCA counter-notice.[145][146] As part of YouTube Music, Universal and YouTube signed an agreement in 2017, which was followed by separate agreements other major labels, which gave the company the right to advertising revenue when its music was played on YouTube.[147] By 2019, creators were having videos taken down or demonetized when Content ID identified even short segments of copyrighted music within a much longer video, with different levels of enforcement depending on the record label.[148] Experts noted that some of these clips said qualified for fair use.[148]

Content ID
Main article: Content ID
In June 2007, YouTube began trials of a system for automatic detection of uploaded videos that infringe copyright. Google CEO Eric Schmidt regarded this system as necessary for resolving lawsuits such as the one from Viacom, which alleged that YouTube profited from content that it did not have the right to distribute.[149] The system, which was initially called "Video Identification"[150][151] and later became known as Content ID,[152] creates an ID File for copyrighted audio and video material, and stores it in a database. When a video is uploaded, it is checked against the database, and flags the video as a copyright violation if a match is found.[153] When this occurs, the content owner has the choice of blocking the video to make it unviewable, tracking the viewing statistics of the video, or adding advertisements to the video.[citation needed]

An independent test in 2009 uploaded multiple versions of the same song to YouTube and concluded that while the system was "surprisingly resilient" in finding copyright violations in the audio tracks of videos, it was not infallible.[154] The use of Content ID to remove material automatically has led to controversy in some cases, as the videos have not been checked by a human for fair use.[155] If a YouTube user disagrees with a decision by Content ID, it is possible to fill in a form disputing the decision.[156] Before 2016, videos were not monetized until the dispute was resolved. Since April 2016, videos continue to be monetized while the dispute is in progress, and the money goes to whoever won the dispute.[157] Should the uploader want to monetize the video again, they may remove the disputed audio in the "Video Manager".[158] YouTube has cited the effectiveness of Content ID as one of the reasons why the site's rules were modified in December 2010 to allow some users to upload videos of unlimited length.[159]

Russia
In 2021, two accounts linked to RT DE, the German channel of the Russian state-owned RT network, were removed for breaching YouTube's policies relating to COVID-19.[160] Russia threatened to ban YouTube after the platform deleted two German RT channels in September 2021.[161] Shortly after the Russian invasion of Ukraine in 2022, YouTube removed all channels funded by the Russian state.[162] YouTube expanded the removal of Russian content from its site to include channels described as 'pro-Russian'. In June 2022, the War Gonzo channel run by Russian military blogger and journalist Semyon Pegov was deleted.[163]

In July 2023, YouTube removed the channel of British journalist Graham Phillips, active in covering the war in Donbas from 2014.[164] In August 2023, a Moscow court fined Google 3 million rubles, around $35,000, for not deleting what it said was "fake news about the war in Ukraine".[165] In October 2024, a Russian court fined Google 2 undecillion rubles (equivalent to US$20 decillion) for restricting Russian state media channels on YouTube.[166] State news agency TASS reported that Google is allowed to return to the Russian market only if it complies with the court's decision.[167] Kremlin spokesperson Dmitry Peskov labeled the court decision as "symbolic" and warned Google that it "should not be restricting the actions of our broadcasters on its platform."[168]

April Fools gags
See also: List of Google April Fools' Day jokes
YouTube featured an April Fools prank on the site on April 1 of every year from 2008 to 2016. In 2008, all links to videos on the main page were redirected to Rick Astley's music video "Never Gonna Give You Up", a prank known as "rickrolling".[169][170] The next year, when clicking on a video on the main page, the whole page turned upside down, which YouTube claimed was a "new layout".[171] In 2010, YouTube temporarily released a "TEXTp" mode which rendered video imagery into ASCII art letters "in order to reduce bandwidth costs by $1 per second."[172]

The next year, the site celebrated its "100th anniversary" with a range of sepia-toned silent, early 1900s-style films, including a parody of Keyboard Cat.[173] In 2012, clicking on the image of a DVD next to the site logo led to a video about a purported option to order every YouTube video for home delivery on DVD.[174] In 2013, YouTube teamed up with satirical newspaper company The Onion to claim in an uploaded video that the video-sharing website was launched as a contest which had finally come to an end, and would shut down for ten years before being re-launched in 2023, featuring only the winning video. The video starred several YouTube celebrities, including Antoine Dodson. A video of two presenters announcing the nominated videos streamed live for 12 hours.[175][176]

In 2014, YouTube announced that it was responsible for the creation of all viral video trends, and revealed previews of upcoming trends, such as "Clocking", "Kissing Dad", and "Glub Glub Water Dance".[177] The next year, YouTube added a music button to the video bar that played samples from "Sandstorm" by Darude.[178] In 2016, YouTube introduced an option to watch every video on the platform in 360-degree mode with Snoop Dogg.[179]

Services
YouTube Premium
Main article: YouTube Premium

Logo of YouTube Premium
YouTube Premium (formerly Music Key and YouTube Red) is YouTube's premium subscription service. It offers advertising-free streaming, access to original programming, and background and offline video playback on mobile devices.[180] YouTube Premium was originally announced on November 12, 2014, as "Music Key", a subscription music streaming service, and was intended to integrate with and replace the existing Google Play Music "All Access" service.[181][182][183] On October 28, 2015, the service was relaunched as YouTube Red, offering ad-free streaming of all videos and access to exclusive original content.[184][185][186] As of November 2016, the service has 1.5 million subscribers, with a further million on a free-trial basis.[187] As of June 2017, the first season of YouTube Originals had received 250 million views in total.[188]

YouTube Kids
Main article: YouTube Kids

Logo of YouTube Kids
YouTube Kids is an American children's video app developed by YouTube, a subsidiary of Google. The app was developed in response to parental and government scrutiny on the content available to children.[citation needed] The app provides a version of the service oriented towards children, with curated selections of content, parental control features, and filtering of videos deemed inappropriate viewing for children aged under 13, 8 or 5, depending on the age grouping chosen. First released on February 15, 2015, as an Android and iOS mobile app, the app has since been released for LG, Samsung, and Sony smart TVs, as well as for Android TV. On May 27, 2020, it became available on Apple TV. As of September 2019, the app is available in 69 countries, including Hong Kong and Macau, and one province. YouTube launched a web-based version of YouTube Kids on August 30, 2019.[189]

YouTube Music
Main article: YouTube Music

Logo of YouTube Music
On September 28, 2016, YouTube named Lyor Cohen, the co-founder of 300 Entertainment and former Warner Music Group executive, the Global Head of Music.[190] In early 2018, Cohen began hinting at the possible launch of YouTube's new subscription music streaming service, a platform that would compete with other services such as Spotify and Apple Music.[191] On May 22, 2018, the music streaming platform named "YouTube Music" was launched for people who mostly listen to music on YouTube.[192][193][194]

YouTube Movies & TV
YouTube Movies & TV is a video on demand (VOD) service that offers movies and television shows for purchase or rental, depending on availability, along with a selection of movies (encompassing between 100 and 500 titles overall) that are free to stream, with interspersed ad breaks. YouTube began offering free-to-view movie titles to its users in November 2018; selections of new movies are added and others removed, unannounced each month.[195] In March 2021, Google announced plans to gradually deprecate the Google Play Movies & TV app, and eventually migrate all users to the YouTube app's Movies & TV store to view, rent and purchase movies and TV shows (first affecting Roku, Samsung, LG, and Vizio smart TV users on July 15).[196][197] Google Play Movies & TV formally shut down on January 17, 2024, with the web version of that platform migrated to YouTube as an expansion of the Movies & TV store to desktop users. Other functions of Google Play Movies & TV were integrated into the Google TV service.[198]

YouTube Primetime Channels
On November 1, 2022, YouTube launched Primetime Channels, a channel store platform offering third-party subscription streaming add-ons sold a la carte through the YouTube website and app, competing with similar subscription add-on stores operated by Apple, Prime Video and Roku. The add-ons can be purchased through the YouTube Movies & TV hub or through the official YouTube channels of the available services; subscribers of YouTube TV add-ons that are sold through Primetime Channels can also access their content via the YouTube app and website. A total of 34 streaming services (including Paramount+, Showtime, Starz, MGM+, AMC+ and ViX+) were initially available for purchase.[199][200]

NFL Sunday Ticket, as part of a broader residential distribution deal with Google signed in December 2022 that also made it available to YouTube TV subscribers, was added to Primetime Channels as a standalone add-on on August 16, 2023.[201][202] The ad-free tier of Max was added to Primetime Channels on December 12, 2023, coinciding with YouTube TV converting its separate HBO (for base plan subscribers) and HBO Max (for all subscribers) linear/VOD add-ons into a single combined Max offering.[203][204][note 1]

YouTube TV
Main article: YouTube TV

Logo of YouTube TV
On February 28, 2017, in a press announcement held at YouTube Space Los Angeles, YouTube announced YouTube TV, an over-the-top MVPD-style subscription service that would be available for United States customers at a price of US$65 per month. Initially launching in five major markets (New York City, Los Angeles, Chicago, Philadelphia and San Francisco) on April 5, 2017,[205][206] the service offers live streams of programming from the five major broadcast networks (ABC, CBS, The CW, Fox and NBC, along with selected MyNetworkTV affiliates and independent stations in certain markets), as well as approximately 60 cable channels owned by companies such as The Walt Disney Company, Paramount Global, Fox Corporation, NBCUniversal, Allen Media Group and Warner Bros. Discovery (including among others Bravo, USA Network, Syfy, Disney Channel, CNN, Cartoon Network, E!, Fox Sports 1, Freeform, FX and ESPN).[207][208]

Subscribers can receive premium cable channels (including HBO (via a combined Max add-on that includes in-app and log-in access to the service), Cinemax, Showtime, Starz and MGM+) and other subscription services (such as NFL Sunday Ticket, MLB.tv, NBA League Pass, Curiosity Stream and Fox Nation) as optional add-ons for an extra fee, and can access YouTube Premium original content.[207][208] In September 2022, YouTube TV began allowing customers to purchase most of its premium add-ons (excluding certain services such as NBA League Pass and AMC+) without an existing subscription to its base package.[209]

YouTube Go

Logo of YouTube Go
In September 2016, YouTube Go was announced,[210] as an Android app created for making YouTube easier to access on mobile devices in emerging markets. It was distinct from the company's main Android app and allowed videos to be downloaded and shared with other users. It also allowed users to preview videos, share downloaded videos through Bluetooth, and offered more options for mobile data control and video resolution.[211]

In February 2017, YouTube Go was launched in India, and expanded in November 2017 to 14 other countries, including Nigeria, Indonesia, Thailand, Malaysia, Vietnam, the Philippines, Kenya, and South Africa.[212][213] On February 1, 2018, it was rolled out in 130 countries worldwide, including Brazil, Mexico, Turkey, and Iraq. Before it shut down, the app was available to around 60% of the world's population.[214][215] In May 2022, Google announced that they would be shutting down YouTube Go in August 2022.[216]

YouTube Shorts
Main article: YouTube Shorts
Duration: 15 seconds.0:15Subtitles available.CC
An example video which is suitable for YouTube Shorts, showing Crew Dragon Endeavour docking at the International Space Station
In September 2020, YouTube announced that it would be launching a beta version of a new platform of 15-second videos, similar to TikTok, called YouTube Shorts.[217][218] The platform was tested in India and later expanded to other countries, including the United States in March 2021, with videos allowed up to 1 minute long.[219] The platform is not a standalone app, but is integrated into the main YouTube app. Like TikTok, it gives users access to built-in creative tools, including the possibility of adding licensed music to their videos.[220] The platform had its global beta launch on July 13, 2021.[221] On October 15, 2024, the platform officially extended the length of shorts to 3 minutes.[222]

YouTube Stories
In 2018, YouTube started testing a new feature initially called "YouTube Reels".[223] The feature was nearly identical to Instagram Stories and Snapchat Stories. YouTube later renamed the feature "YouTube Stories". It was only available to creators who had more than 10,000 subscribers and could only be posted/seen in the YouTube mobile app.[224] On May 25, 2023, YouTube announced that they would be shutting down this feature on June 26, 2023.[225][226]

YouTube VR
Main article: YouTube VR
In November 2016, YouTube released YouTube VR, a dedicated version with an interface for VR devices, for Google's Daydream mobile VR platform on Android.[227] In November 2018, YouTube VR was released on the Oculus Store for the Oculus Go headset.[227] YouTube VR was updated since for compatibility with successive Quest devices, and was ported to Pico 4.[228]

YouTube VR allows for access to all YouTube-hosted videos, but particularly supports headset access for 360° and 180°-degree video (both in 2D and stereoscopic 3D). Starting with the Oculus Quest, the app was updated for compatibility with mixed-reality passthrough modes on VR headsets. In April 2024, YouTube VR was updated to support 8K SDR video on Meta Quest 3.[229]

Playables
In 2010, YouTube added Snake as a hidden game inside of their video player.[230] In May 2024, YouTube introduced Playables, a set of around 75 free-to-play games that can be played on the platform.[231]

Automatic language dubbing
In December 2024, YouTube added the functionality of automatic language dubbing, which uses AI to produce translations of videos into different languages.[232][233][234][235]

Criticism and controversies
This section is an excerpt from YouTube moderation.[edit]
YouTube, a video sharing platform, has faced various criticisms over the years, particularly regarding content moderation, offensive content, and monetization. YouTube has faced criticism over aspects of its operations,[236] its recommendation algorithms perpetuating videos that promote conspiracy theories and falsehoods,[237] hosting videos ostensibly targeting children but containing violent or sexually suggestive content involving popular characters,[238] videos of minors attracting pedophilic activities in their comment sections,[239] and fluctuating policies on the types of content that is eligible to be monetized with advertising.[236]

YouTube has also been blocked by several countries. As of 2018, public access to YouTube was blocked by countries including China, North Korea, Iran, Turkmenistan,[240] Uzbekistan,[241][242] Tajikistan, Eritrea, Sudan and South Sudan.

Privacy concerns
This section is an excerpt from YouTube and privacy.[edit]
Since its founding in 2005, the American video-sharing website YouTube has been faced with a growing number of privacy issues, including allegations that it allows users to upload unauthorized copyrighted material and allows personal information from young children to be collected without their parents' consent.

In September 2024, the Federal Trade Commission released a report summarizing 9 company responses (including from YouTube) to orders made by the agency pursuant to Section 6(b) of the Federal Trade Commission Act of 1914 to provide information about user and non-user data collection (including of children and teenagers) and data use by the companies that found that the companies' user and non-user data practices put individuals vulnerable to identity theft, stalking, unlawful discrimination, emotional distress and mental health issues, social stigma, and reputational harm.[243][244][245]

Censorship and bans
Main article: Censorship of YouTube
State censorship of YouTube content
YouTube has been censored, filtered, or banned for a variety of reasons, including:[246]

Limiting public access and exposure to content that may ignite social or political unrest.

The majority of YouTube's advertising revenue goes to the publishers and video producers who hold the rights to their videos; the company retains 45% of the ad revenue.[375] In 2010, it was reported that nearly a third of the videos with advertisements were uploaded without permission of the copyright holders. YouTube gives an option for copyright holders to locate and remove their videos or to have them continue running for revenue.[376] In May 2013, Nintendo began enforcing its copyright ownership and claiming the advertising revenue from video creators who posted screenshots of its games.[377] In February 2015, Nintendo agreed to share the revenue with the video creators through the Nintendo Creators Program.[378][379][380] On March 20, 2019, Nintendo announced on Twitter that the company will end the Creators program. Operations for the program ceased on March 20, 2019.[381][382]`
const testing= document.getElementById("testing");
const importbtn= document.getElementById("import");
const exportbtn= document.getElementById("export");
// this part is ai generated
const KEYS = [
    // ROW 1 (Top)
    { x: 0,   y: 0, finger: 0 },
    { x: 19,  y: 0, finger: 1 },
    { x: 38,  y: 0, finger: 2 },
    { x: 57,  y: 0, finger: 3 },
    { x: 76,  y: 0, finger: 3 },
    { x: 95,  y: 0, finger: 4 },
    { x: 114, y: 0, finger: 4 },
    { x: 133, y: 0, finger: 5 },
    { x: 152, y: 0, finger: 6 },
    { x: 171, y: 0, finger: 7 },

    // ROW 2 (Home)
    { x: 5,   y: 19, finger: 0 },
    { x: 24,  y: 19, finger: 1 },
    { x: 43,  y: 19, finger: 2 },
    { x: 62,  y: 19, finger: 3 },
    { x: 81,  y: 19, finger: 3 },
    { x: 100, y: 19, finger: 4 },
    { x: 119, y: 19, finger: 4 },
    { x: 138, y: 19, finger: 5 },
    { x: 157, y: 19, finger: 6 },

    // ROW 3 (Bottom)
    { x: 10,  y: 38, finger: 0 },
    { x: 29,  y: 38, finger: 1 },
    { x: 48,  y: 38, finger: 2 },
    { x: 67,  y: 38, finger: 3 },
    { x: 86,  y: 38, finger: 3 },
    { x: 105, y: 38, finger: 4 },
    { x: 124, y: 38, finger: 4 }
];

const FINGER_STIFFNESS = [2.5, 1.6, 1.2, 1.0, 1.0, 1.2, 1.6, 2.5];

const REST_COORDS = [
    { x: 5,   y: 19, finger: 0 }, // 0: L.Pinky
    { x: 24,  y: 19, finger: 1 }, // 1: L.Ring
    { x: 43,  y: 19, finger: 2 }, // 2: L.Middle
    { x: 62,  y: 19, finger: 3 }, // 3: L.Index
    { x: 119, y: 19, finger: 4 }, // 4: R.Index
    { x: 138, y: 19, finger: 5 }, // 5: R.Middle
    { x: 157, y: 19, finger: 6 }, // 6: R.Ring
    { x: 176, y: 19, finger: 7 }  // 7: R.Pinky
];
//ai generated part end


importbtn.addEventListener("click",()=>{
    let input = document.createElement('input');
    input.type = 'file';
    input.accept = '.json,application/json';
    input.onchange = e => { 
        let file = e.target.files[0]; 
        let reader = new FileReader();
        reader.readAsText(file,'UTF-8');
        reader.onload = readerEvent => {
            let content = readerEvent.target.result;
            try{
                let layout=JSON.parse(content);
                if(!Array.isArray(layout) || layout.length!==26){
                    alert("Invalid layout file");
                    return;
                }
                window.bestLayout=layout;
                showLayout(layout);
            }catch(err){
                alert("Error parsing layout file: "+err.message);
            }
        }
    }
    input.click();
})
exportbtn.addEventListener("click",()=>{
    if(!window.bestLayout){return}
    let jsonLayout=JSON.stringify(window.bestLayout)
    let blob = new Blob([jsonLayout], {type: "application/json"});
    let url = URL.createObjectURL(blob);
    let a = document.createElement("a");
    a.href=url
    a.download="layout.json"
    a.click();
})


function calculateOneStrain(key1,key2){
    if (key1.finger!==key2.finger){
        alert("Keys must be pressed by the same finger to calculate a strain");
        throw new Error("Keys must be pressed by the same finger to calculate a strain");
    }
    let homecoords = REST_COORDS[key1.finger];
    let homedx = key2.x - homecoords.x;
    let homedy = key2.y - homecoords.y;
    let homedistance = Math.sqrt(homedx*homedx + homedy*homedy);
    let stiffness = FINGER_STIFFNESS[key1.finger];
    let static= 0.5 * stiffness * homedistance * homedistance;
    if (key1.x===key2.x && key1.y===key2.y){
        return static;
    }
    let dx = key2.x - key1.x;
    let dy = key2.y - key1.y;
    let distance = Math.sqrt(dx*dx + dy*dy);
    let travel = 0.5 * stiffness * (distance - homedistance) * (distance - homedistance);
    return static + travel;
}
function calculateTotalStrain(layout){
    let totalStrain = 0;
    let fingers = REST_COORDS;
    for (let i = 0; i < cleanedtrainingdata.length - 1; i++) {
        let ch=cleanedtrainingdata.charAt(i);
        let key= KEYS[layout.findIndex(k=>k===ch)];
        let ikey=fingers[key.finger];
        let dstrain = calculateOneStrain(ikey,key)//the strain to move from one key to another
        fingers[key.finger]=key;
        let sstrain = 0;//the strain to keep the finger where it is
        for (let f=0;f<8;f++){
            if(f===key.finger) continue;
            sstrain+=calculateOneStrain(fingers[f],fingers[f]);
        } 
        totalStrain += dstrain + sstrain;
    }
    return totalStrain;
}

var cleanedtrainingdata="";
const cleandata=()=>{
    cleanedtrainingdata=trainingdata.value.toLowerCase().replace(/[^a-z]/g,"");
    console.log(cleanedtrainingdata.slice(0,100));
    window.qwertyeff = calculateTotalStrain(["q","w","e","r","t","y","u","i","o","p",
"a","s","d","f","g","h","j","k","l",
"z","x","c","v","b","n","m"])
    qwertyspan.innerText=window.qwertyeff
}
cleandata();
trainingdata.addEventListener("input",cleandata)
function combineLayout(layout1,layout2){
    let len = layout1.length;
    let newlayout = new Array(len);
    let start = Math.floor(Math.random() * len);
    let end = Math.floor(Math.random() * len);
    if (start > end) [start, end] = [end, start];
    for (let i = start; i <= end; i++) {
        newlayout[i] = layout1[i];
    }
    let parent2Index = 0;
    for (let i = 0; i < len; i++) {
        if (newlayout[i] === undefined) {
            // Find next key from parent2 not already in newlayout
            while (newlayout.includes(layout2[parent2Index])) {
                parent2Index++;
            }
            newlayout[i] = layout2[parent2Index];
            parent2Index++;
        }
    }
    if (Math.random() < 0.8) {
        let idx1 = Math.floor(Math.random() * len);
        let idx2 = Math.floor(Math.random() * len);
        [newlayout[idx1], newlayout[idx2]] = [newlayout[idx2], newlayout[idx1]];
    }
    
    return newlayout;
}
/*console.log(combineLayout(["q","w","e","r","t","y","u","i","o","p",
"a","s","d","f","g","h","j","k","l",
"z","x","c","v","b","n","m"],
["m","n","b","v","c","x","z","l","k","j",
"h","g","f","d","s","a","p","o","i",
"u","y","t","r","e","w","q"]));*/
function shuffle(array) {
    const newArray = [...array]; // Create a copy
    let currentIndex = newArray.length, randomIndex;

    while (currentIndex !== 0) {
        randomIndex = Math.floor(Math.random() * currentIndex);
        currentIndex--;
        [newArray[currentIndex], newArray[randomIndex]] = [newArray[randomIndex], newArray[currentIndex]];
    }

    return newArray;
}
function showLayout(layout){
    let keys=lastkb.querySelectorAll(".lkey")
    for(let i=0;i<26;i+=1){
        keys[i].innerText=layout[i];
    }
}
async function startTheTraining(){
    let populationSize=parseInt(populationsizeinput.value);
    let generations=parseInt(generationsinput.value);
    let population=[];
    let bestLayout=null;
    let bestStrain=9999999999;
    let allChars=["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"]
    for (let i=0;i<populationSize;i++){
        let layout=shuffle(allChars);
        let strain=calculateTotalStrain(layout);
        population.push({layout:layout,strain:strain});
        if (strain<bestStrain){
            bestStrain=strain;
            bestLayout=layout;
            showLayout(bestLayout);
        }
    }
    console.log("initial best strain",bestStrain);
    statusspan.innerText=`Starting evolution for ${generations} generations. Current best: ${bestStrain.toFixed(2)} (lower is better)`;
    for (let gen=0;gen<generations;gen++){
        let newPopulation=[];
        //elitism: carry over the best 10 layouts
        population.sort((a,b)=>a.strain-b.strain);
        for (let i=0;i<Math.min(10,populationSize);i++){
            newPopulation.push(population[i]);
        }
        //pick the top ceil(sqrt(populationSize)) layouts to be parents
        population.sort((a,b)=>a.strain-b.strain);
        let topCount=Math.ceil(Math.sqrt(populationSize));
        let topLayouts=population.slice(0,topCount);
        //combine them to create new layouts and pick the populationSize best ones
        while (newPopulation.length<populationSize){
            let parent1=topLayouts[Math.floor(Math.random()*topLayouts.length)];
            let parent2=topLayouts[Math.floor(Math.random()*topLayouts.length)];
            let childLayout=combineLayout(parent1.layout,parent2.layout);
            let childStrain=calculateTotalStrain(childLayout);
            newPopulation.push({layout:childLayout,strain:childStrain});
            if (childStrain<bestStrain){
                bestStrain=childStrain;
                bestLayout=childLayout;
                showLayout(bestLayout);
                console.log("new best strain",bestStrain);
            }
        }
        population=newPopulation.sort((a,b)=>a.strain-b.strain).slice(0,populationSize);
    statusspan.innerHTML=`${gen+1}/${generations} complete, current best ${bestStrain.toFixed(0)}.<br> ${(100-100*(bestStrain/window.qwertyeff)).toFixed(0)}% better than QWERTY`;
        
            await new Promise(resolve => setTimeout(resolve, 0));

    }
    console.log("final best strain",bestStrain);
    console.log("final best layout",bestLayout);
    window.bestLayout=bestLayout;
    effspan.innerText=bestStrain
    showLayout(bestLayout);
}
starttrainingbtn.addEventListener("click",startTheTraining);
